In [1]:
#Q1
from scipy.spatial import distance
A=(1,2,3,4,5,6)
B=(7,8,9,10,11,12)
A,B
minkowski_distance = distance.minkowski(A, B, p=3)
print('Minkowski Distance b/w', A, 'and', B, 'is: ', minkowski_distance)

Minkowski Distance b/w (1, 2, 3, 4, 5, 6) and (7, 8, 9, 10, 11, 12) is:  10.902723556992836


In [2]:
#Q2
import numpy as np
a = np.arange(9).reshape((3,3))
print("Original flattened array:")
print(a)
print("Weighted average along the specified axis of the above flattened array:")
print(np.average(a, axis=1, weights=[1./4, 2./4, 2./4]))


Original flattened array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Weighted average along the specified axis of the above flattened array:
[1.2 4.2 7.2]


In [3]:
#Q3
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array2:")
print(y)
print("\nCross-correlation of the said arrays:\n",np.cov(x, y))



Original array1:
[0 1 3]

Original array2:
[2 4 5]

Cross-correlation of the said arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


In [4]:
import io
import pandas as pd
df = pd.read_csv("titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [6]:
df.mean()

C:\Users\anant\AppData\Local\Temp\ipykernel_1448\3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [7]:
df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [8]:
import io
import pandas as pd
df = pd.read_csv("nursery-growers-and-greenhouse.csv")
df

County  License Number                   Operation Type  \
0       SULLIVAN        481241.0               Nursery Stock Only   
1       TOMPKINS        504934.0               Nursery Stock Only   
2           ERIE        146689.0               Nursery Stock Only   
3         SENECA        450323.0               Nursery Stock Only   
4        NIAGARA        645162.0               Nursery Stock Only   
...          ...             ...                              ...   
2802   SCHOHARIE        644545.0  Combined Nursery and Greenhouse   
2803  CHAUTAUQUA        646019.0            Greenhouse Stock Only   
2804      ORANGE        644489.0  Combined Nursery and Greenhouse   
2805     SUFFOLK        474599.0  Combined Nursery and Greenhouse   
2806        ERIE        142973.0               Nursery Stock Only   

          Nursery Size               Greenhouse Size  \
0         11-100 Acres                           NaN   
1     10 Acres or Less                           NaN   
2     10 Acres or Less                           NaN   
3     10 Acres or Less                           NaN   
4     10 Acres or Less                           NaN   
...                ...                           ...   
2802  10 Acres or Less    2,001-20,000 SqFt of Glass   
2803               NaN   2,000 SqFt of Glass or Less   
2804  10 Acres or Less   2,000 SqFt of Glass or Less   
2805  10 Acres or Less  20,001 SqFt of Glass or More   
2806      11-100 Acres                           NaN   

                       Trade Name                      Owner Name  \
0     MAPLEHORST FARM NURSERY INC                    JOHN W. RAPP   
1                 HUNTS TREE FARM                   HUNT ROBERT F   
2               BLAKE TOM VEHICLE                       BLAKE TOM   
3            KINGDOM ROAD NURSERY                 BRADLEY MICHAEL   
4                    GUY KORNAKER                    GUY KORNAKER   
...                           ...                             ...   
2802      SUNNYCREST ORCHARDS INC                  LAURIE SCHMITT   
2803    SAUNTERING ROOTS FARM LLC  BRANDI JO & ANDREW DALE NYBERG   
2804       MAJOR BLOSSOM FARM LLC          MAJOR BLOSSOM FARM LLC   
2805         GLASS GREENHOUSE THE            GABRIELSEN WALTER JR   
2806      LAKESIDE SOD SPLY CO IN      LAKESIDE SOD SUPPLY CO INC   

     Business Phone Street Number             Street Name Address Line 2  \
0      845-794-8596           151               RAPP ROAD            NaN   
1      607-539-7582           146      BLACKMAN HILL ROAD            NaN   
2      716-822-7610            91             TAMPA DRIVE            NaN   
3      315-568-9607          2922            KINGDOM ROAD            NaN   
4      716-550-3152           309         DIVISION STREET            NaN   
...             ...           ...                     ...            ...   
2802   518-284-2256          7869          STATE ROUTE 10            NaN   
2803   716-489-8090          4927             POTTER ROAD            NaN   
2804   917-250-0626          5098                  RT 17M            NaN   
2805   631-722-2121          1350               MAIN ROAD            NaN   
2806   716-741-2877           NaN  ROBNETT FARM-HAKE ROAD            NaN   

     Address Line 3             City State  Zip Code  \
0               NaN       MONTICELLO    NY     12701   
1               NaN        BERKSHIRE    NY     13736   
2               NaN          BUFFALO    NY     14220   
3               NaN         WATERLOO    NY     13165   
4               NaN  NORTH TONAWANDA    NY     14120   
...             ...              ...   ...       ...   
2802            NaN   SHARON SPRINGS    NY     13459   
2803            NaN         MAYVILLE    NY     14757   
2804            NaN      NEW HAMPTON    NY     10958   
2805            NaN        JAMESPORT    NY     11947   
2806            NaN            AKRON    NY     14001   

                                           Georeference  New York Zip Codes 2  \
0     {'type

In [9]:
print("Given Dataframe is :\n",df)
   
# bydefault splitting is done on the basis of single space.
print("\nSplitting 'Name' column into two different columns :\n",df.City.str.split(expand=True))

Given Dataframe is :
           County  License Number                   Operation Type  \
0       SULLIVAN        481241.0               Nursery Stock Only   
1       TOMPKINS        504934.0               Nursery Stock Only   
2           ERIE        146689.0               Nursery Stock Only   
3         SENECA        450323.0               Nursery Stock Only   
4        NIAGARA        645162.0               Nursery Stock Only   
...          ...             ...                              ...   
2802   SCHOHARIE        644545.0  Combined Nursery and Greenhouse   
2803  CHAUTAUQUA        646019.0            Greenhouse Stock Only   
2804      ORANGE        644489.0  Combined Nursery and Greenhouse   
2805     SUFFOLK        474599.0  Combined Nursery and Greenhouse   
2806        ERIE        142973.0               Nursery Stock Only   

          Nursery Size               Greenhouse Size  \
0         11-100 Acres                           NaN   
1     10 Acres or Less               

In [10]:
from numpy import mean
df.groupby(["City"]).mean()

License Number  Zip Code  New York Zip Codes 2  Counties 2  \
City                                                                           
ACCORD             546465.250000   12404.0                  80.0      2182.0   
ADAMS              220796.000000   13605.0                1469.0      2089.0   
ADAMS CENTER       225978.000000   13606.0                1470.0      2089.0   
ADDISON            501989.800000   14801.0                1748.0      2178.0   
AFTON              337734.500000   13730.0                1625.0      2035.0   
...                          ...       ...                   ...         ...   
YORK               645348.000000   14592.0                 371.0      2091.0   
YORKSHIRE          344218.000000   14173.0                 267.5      2034.0   
YORKTOWN HEIGHTS   582098.166667   10598.0                1352.0      2185.0   
YOUNGSTOWN         644405.500000   14174.0                  31.0      2131.0   
YOUNGSVILLE        485712.000000   12791.0                 781.0      2180.0   

                  NYS Municipal Boundaries 2  
City                                          
ACCORD                                 413.0  
ADAMS                                  853.0  
ADAMS CENTER                           844.0  
ADDISON                                 38.8  
AFTON                                  607.5  
...                                      ...  
YORK                                   732.0  
YORKSHIRE                              374.0  
YORKTOWN HEIGHTS                       947.5  
YOUNGSTOWN                             156.0  
YOUNGSVILLE                            663.0  

[859 rows x 5 columns]

In [11]:
#Q6 Arithmetic mean
import pandas as pd
import numpy as np
data={'Name':pd.Series(['Hikigaya','Hisoka','Roy','Joseph','Gojo','Yato','Spike','Kakashi','Saitama','Rem']),'Python':pd.Series([80,82,60,72,88,87,61,89,81,96]),'Electronics':pd.Series([72,92,77,89,73,91,75,92,93,76]),'Statistics':pd.Series([78,77,68,62,88,76,63,98,93,67]),'FDS':([90,94,80,73,95,93,67,97,65,89]),'TCS':([88,68,69,65,58,84,72,91,75,89])}
df=pd.DataFrame(data)
df

Name  Python  Electronics  Statistics  FDS  TCS
0  Hikigaya      80           72          78   90   88
1    Hisoka      82           92          77   94   68
2       Roy      60           77          68   80   69
3    Joseph      72           89          62   73   65
4      Gojo      88           73          88   95   58
5      Yato      87           91          76   93   84
6     Spike      61           75          63   67   72
7   Kakashi      89           92          98   97   91
8   Saitama      81           93          93   65   75
9       Rem      96           76          67   89   89

In [12]:
result=pd.DataFrame.mean(df)
print('Arithmetic Mean:',result)
df

Arithmetic Mean: Python         79.6
Electronics    83.0
Statistics     77.0
FDS            84.3
TCS            75.9
dtype: float64


C:\Users\anant\AppData\Local\Temp\ipykernel_1448\4110429651.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  result=pd.DataFrame.mean(df)


Name  Python  Electronics  Statistics  FDS  TCS
0  Hikigaya      80           72          78   90   88
1    Hisoka      82           92          77   94   68
2       Roy      60           77          68   80   69
3    Joseph      72           89          62   73   65
4      Gojo      88           73          88   95   58
5      Yato      87           91          76   93   84
6     Spike      61           75          63   67   72
7   Kakashi      89           92          98   97   91
8   Saitama      81           93          93   65   75
9       Rem      96           76          67   89   89

In [13]:
#Row wise geometric mean
import scipy
from scipy import stats
df['Geometric Mean']=stats.gmean(df.iloc[:, 1:3], axis=1)
df

Name  Python  Electronics  Statistics  FDS  TCS  Geometric Mean
0  Hikigaya      80           72          78   90   88       75.894664
1    Hisoka      82           92          77   94   68       86.856203
2       Roy      60           77          68   80   69       67.970582
3    Joseph      72           89          62   73   65       80.049984
4      Gojo      88           73          88   95   58       80.149860
5      Yato      87           91          76   93   84       88.977525
6     Spike      61           75          63   67   72       67.638746
7   Kakashi      89           92          98   97   91       90.487568
8   Saitama      81           93          93   65   75       86.792857
9       Rem      96           76          67   89   89       85.416626

In [14]:
#column wise Geometric mean
Python=scipy.stats.gmean(df.loc[:, "Python"])
print("Geometric mean of Python=",Python)
Electronics=scipy.stats.gmean(df.loc[:, "Electronics"])
print("Geometric mean of Electronics=",Electronics)
Statistics=scipy.stats.gmean(df.loc[:, "Statistics"])
print("Geometric mean of Statistics=",Statistics)
FDS=scipy.stats.gmean(df.loc[:, "FDS"])
print("Geometric mean of FDS=",FDS)
TCS=scipy.stats.gmean(df.loc[:, "TCS"])
print("Geometric mean of TCS=",TCS)

Geometric mean of Python= 78.73839546206867
Geometric mean of Electronics= 82.55646602886054
Geometric mean of Statistics= 76.10105142357588
Geometric mean of FDS= 83.46683898478051
Geometric mean of TCS= 75.11534167783806


In [15]:
#Row wise Harmonic mean
import scipy
from scipy import stats
scipy.stats.hmean(df.iloc[:,1:3],axis=1)

array([75.78947368, 86.71264368, 67.44525547, 79.60248447, 79.80124224,
       88.95505618, 67.27941176, 90.47513812, 86.5862069 , 84.8372093 ])

In [16]:
#column wise Harmonic mean
Python=scipy.stats.hmean(df.loc[:,"Python"])
print("Harmonic mean of Python =",Python)
Electronics=scipy.stats.hmean(df.loc[:,"Electronics"])
print("Harmonic mean of Electronics =",Electronics)
Statistics=scipy.stats.hmean(df.loc[:,"Statistics"])
print("Harmonic mean of SDtatistics =",Statistics)
FDS=scipy.stats.hmean(df.loc[:,"FDS"])
print("Harmonic mean of FDS =",FDS)
TCS=scipy.stats.hmean(df.loc[:,"TCS"])
print("Harmonic mean of TCS =",TCS)

Harmonic mean of Python = 77.82082387235585
Harmonic mean of Electronics = 82.11357400811033
Harmonic mean of SDtatistics = 75.23371523041008
Harmonic mean of FDS = 82.58847816707808
Harmonic mean of TCS = 74.32721759785491


In [17]:
#Q7 Pandas Profiling
#pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

In [18]:
import pandas as pd
df = pd.read_csv("titanic.csv")
print(df.shape)
df.head()

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [19]:
import numpy as np
import seaborn as sns

In [20]:
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport
df = pd.DataFrame(np.random.rand(100, 5), columns=["a", "b", "c", "d", "e"])

In [21]:
profile=ProfileReport(df, title="Pandas Profiling Report")

In [22]:
profile=ProfileReport(df, title="Pandas Profiling Report", explorative=True)

In [23]:
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
profile.to_notebook_iframe()

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [25]:
profile.to_file("your_report.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [26]:
# as a string
json_data = profile.to_json()

Render JSON:   0%|          | 0/1 [00:00<?, ?it/s]

In [27]:
#as a file
profile.to_file("your_report.json")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [28]:
profile = ProfileReport(df, minimal=True)
profile.to_file(output_file="REPORT.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
#! ls - this is for linux
! dir
#above one is for windows

 Volume in drive D is Drive
 Volume Serial Number is 40A7-E091

 Directory of D:\Prog\Python\FDS\Ass2

02-02-2022  16:15    <DIR>          .
02-02-2022  14:04    <DIR>          ..
02-02-2022  15:47    <DIR>          .ipynb_checkpoints
19-09-2019  03:05             5,107 Iris.csv
01-01-2021  08:53           675,377 nursery-growers-and-greenhouse.csv
02-02-2022  16:15           551,662 REPORT.html
02-02-2022  15:08            10,894 setA.ipynb
02-02-2022  15:14            15,461 setB.ipynb
02-02-2022  16:15            86,082 setC.ipynb
02-02-2022  16:08         5,789,258 setCq7.ipynb
11-12-2019  07:47            61,194 titanic.csv
02-02-2022  16:15         1,180,908 your_report.html
02-02-2022  16:15           741,990 your_report.json
              10 File(s)      9,117,933 bytes
               3 Dir(s)  301,042,892,800 bytes free


In [30]:
#! cat REPORT.html - this is for linux
! type REPORT.html
#above one is for windows

<!doctype html><html lang=en><head><meta charset=utf-8><meta name=viewport content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name=description content="Profile report generated with the `pandas-profiling` Python package"><meta name=author content="Simon Brugman and the open source community."><meta name=generator content="Pandas Profiling v3.1.1"><meta name=url content=https://github.com/pandas-profiling/pandas-profiling><meta name=date content="2022-02-02 10:45:52.929655"><title>Pandas Profiling Report</title><style>
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canv