In [1]:
import io
import pandas as pd
df = pd.read_csv('winequality-red.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [2]:
#2 Rescaling data
import pandas as pd
import numpy as np
from sklearn import preprocessing
import scipy.stats as s
print("\n\n Data Scaled between 0 to 1")
data_scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled = data_scaler.fit_transform(df)
print("\n Min Max Scaled Data")
print("----------------------")
print(data_scaled.round(2))




 Data Scaled between 0 to 1

 Min Max Scaled Data
----------------------
[[0.25 0.4  0.   ... 0.14 0.15 0.4 ]
 [0.28 0.52 0.   ... 0.21 0.22 0.4 ]
 [0.28 0.44 0.04 ... 0.19 0.22 0.4 ]
 ...
 [0.15 0.27 0.13 ... 0.25 0.4  0.6 ]
 [0.12 0.36 0.12 ... 0.23 0.28 0.4 ]
 [0.12 0.13 0.47 ... 0.2  0.4  0.6 ]]


In [3]:
#3 standardizing data
print("\n Standardizing data")
print("------------------------")
X_train=df
print("Original data \n",X_train)
print("\n Initial mean:",s.tmean(X_train).round(2))
print("Initial Standard Deviation:",round(X_train.std(),2))
X_scaled = preprocessing.scale(X_train)
X_scaled.mean(axis=0)
X_scaled.std(axis=0)
print("\n Standardized data \n",X_scaled.round(2))
print("\n scaled mean: ",s.tmean(X_scaled).round(2))
print("Scaled Standard Deviation: ",round(X_scaled.std(),2))



 Standardizing data
------------------------
Original data 
       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0

In [4]:
#4 Normalizing data
dn = preprocessing.normalize(df, norm='l1')
print("\n L1 Normalized data")
print("-------------")
print(dn.round(2))


 L1 Normalized data
-------------
[[0.1  0.01 0.   ... 0.01 0.13 0.07]
 [0.06 0.01 0.   ... 0.01 0.08 0.04]
 [0.08 0.01 0.   ... 0.01 0.1  0.05]
 ...
 [0.06 0.01 0.   ... 0.01 0.11 0.06]
 [0.06 0.01 0.   ... 0.01 0.1  0.05]
 [0.06 0.   0.01 ... 0.01 0.12 0.06]]


In [5]:
# 5 Binarize data
data_binarized = preprocessing.Binarizer(threshold=2).transform(df)
print("\n Binarized data")
print("\n -----------------")
print(data_binarized)


 Binarized data

 -----------------
[[1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 ...
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]
 [1. 0. 0. ... 0. 1. 1.]]


C:\Users\anant\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but Binarizer was fitted without feature names
  warnings.warn(
